{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.4.0.jar",
          "url": "room-common-2.4.0.jar",
          "size": 24749,
          "sha512": "50e9fdf0f246aef698a288878ebd0c12f4c718451a49cdd1a57d242bb877ea5fb7339231e6ec0dbd9d92ed27316c8ce7a0c829da78e8e58743d7088ad4238cb7",
          "sha256": "6505f987e696f54475cd82c922e4f4df8c6cd5282e2601bf118e1de7320c36cf",
          "sha1": "63d9f9cb245ee9b4c8ebb8aca201661f99583ffa",
          "md5": "159783b553dc0fc7adba80f7d667db75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.4.0.jar",
          "url": "room-common-2.4.0.jar",
          "size": 24749,
          "sha512": "50e9fdf0f246aef698a288878ebd0c12f4c718451a49cdd1a57d242bb877ea5fb7339231e6ec0dbd9d92ed27316c8ce7a0c829da78e8e58743d7088ad4238cb7",
          "sha256": "6505f987e696f54475cd82c922e4f4df8c6cd5282e2601bf118e1de7320c36cf",
          "sha1": "63d9f9cb245ee9b4c8ebb8aca201661f99583ffa",
          "md5": "159783b553dc0fc7adba80f7d667db75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-common-2.4.0-sources.jar",
          "url": "room-common-2.4.0-sources.jar",
          "size": 56543,
          "sha512": "288fd4c012f9467f7f64a2b18f1e9f754273ecd2595f78410fea2f909cf92d0c9c379b04f86bcd62815af1eafa0e971f0664cf72f21778552776fe4da16c90ba",
          "sha256": "135804745d5c54f75bc04a7c4488f12dbdaf3e79b43a61d0b38b8c7ce0495922",
          "sha1": "261d22e04e0c7a0cb9437cb6052a6561a7c3d300",
          "md5": "1b72571231985fa714722a6b8223d364"
        }
      ]
    }
  ]
}
