{
  "formatVersion": "1.1",
  "component": {
    "group": "com.airbnb.android",
    "module": "lottie-compose",
    "version": "1.0.0-beta03-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "mpkadxzqxvav5kzrn574hoae2e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lottie-compose-1.0.0-beta03-1.aar",
          "url": "lottie-compose-1.0.0-beta03-1.aar",
          "size": 53399,
          "sha512": "0cf39049ff32d65aebb1d6deb002cec73d879f0397c2fc194df4a13a1589fb274413cb87877dd87bd73acd6b3b124da51b01a3dd7f344fe8d984e3558eabf154",
          "sha256": "54fd89a9516af4d27ff375b6bfd3aaa6621995ab8b302b1675dc736180416975",
          "sha1": "76ed776860e537818a18ae9b5e565ceb584670f3",
          "md5": "4949801a3bf92b615604b303e2bbd8f8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "lottie-compose-1.0.0-beta03-1.aar",
          "url": "lottie-compose-1.0.0-beta03-1.aar",
          "size": 53399,
          "sha512": "0cf39049ff32d65aebb1d6deb002cec73d879f0397c2fc194df4a13a1589fb274413cb87877dd87bd73acd6b3b124da51b01a3dd7f344fe8d984e3558eabf154",
          "sha256": "54fd89a9516af4d27ff375b6bfd3aaa6621995ab8b302b1675dc736180416975",
          "sha1": "76ed776860e537818a18ae9b5e565ceb584670f3",
          "md5": "4949801a3bf92b615604b303e2bbd8f8"
        }
      ]
    }
  ]
}
