{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.0.aar",
          "url": "room-ktx-2.4.0.aar",
          "size": 35461,
          "sha512": "c795e82e9b2ca7a273e10a8dcaad370dfd8da57f7821067cbfb6f09bb359bdf4ad8303b4d52f002b9d7fb902772d2d019d816cff96e086b1eba260eeb68cc211",
          "sha256": "08be5af250ef4a201c157eec693578c86b6030acf85ccd75f06cec8f4a651429",
          "sha1": "dbe7ddf2322c07c71a170e7ee3f5318d6166414e",
          "md5": "a875cc8a12b111c42e1a363a7d83b03e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.0.aar",
          "url": "room-ktx-2.4.0.aar",
          "size": 35461,
          "sha512": "c795e82e9b2ca7a273e10a8dcaad370dfd8da57f7821067cbfb6f09bb359bdf4ad8303b4d52f002b9d7fb902772d2d019d816cff96e086b1eba260eeb68cc211",
          "sha256": "08be5af250ef4a201c157eec693578c86b6030acf85ccd75f06cec8f4a651429",
          "sha1": "dbe7ddf2322c07c71a170e7ee3f5318d6166414e",
          "md5": "a875cc8a12b111c42e1a363a7d83b03e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-ktx-2.4.0-sources.jar",
          "url": "room-ktx-2.4.0-sources.jar",
          "size": 6172,
          "sha512": "de695411f2de0eaddbceef38442573f628afbdeabe4a2ffc5564014f4106e4a0e8eeabc78acbe441598786b2e3929f9bd8d42d82ad44c02b13f244753814f566",
          "sha256": "216fd66c14a6c91f9488270add0604bebaa705e51309459a59cb33dc98343e46",
          "sha1": "8d0b5588d76f4f7843b5bc174d3a168604c285ad",
          "md5": "0e7ac736a01dac2aff569eeb682709fb"
        }
      ]
    }
  ]
}
